module.exports = {
    ETRADE_AUTH: 'ETRADE_AUTH',
    ETRADE_SESSION: 'ETRADE_SESSION',
    ETRADE_SET_ACCOUNTS: 'ETRADE_SET_ACCOUNTS',
    ETRADE_SET_ACCOUNT: 'ETRADE_SET_ACCOUNT',
    ETRADE_SET_PORTFOLIO: 'ETRADE_SET_PORTFOLIO'
  };
  